In [1]:
import torch

# Tensors

In [5]:
# At its core, PyTorch is a library for processing tensors.
# A tensor is a number, vector, matrix or any n-dimensional array.
# single number
t1 = torch.tensor(1.)
t1,t1.dtype

(tensor(1.), torch.float32)

In [7]:
# Vector
t2 = torch.tensor([1.,2,3,4])
t2,t2.dtype

(tensor([1., 2., 3., 4.]), torch.float32)

In [9]:
# Matrix
t3= torch.tensor([[1.,2],[3,4],[5,6]])
t3,t3.dtype

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]), torch.float32)

In [16]:
# 3-dim array 
# it can extend to n-dim
t4 = torch.tensor([[[1.,2],[3,4]],
                   [[1,2],[3,4]],
                   [[1,2],[3,4]]
                   ])
t4

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])

In [25]:
# using .shape to check tensor's shape
t1.shape,t2.shape,t3.shape,t4.shape

(torch.Size([]), torch.Size([4]), torch.Size([3, 2]), torch.Size([3, 2, 2]))

# Tensor operations and gradients

In [33]:
# create tensors
x = torch.tensor(1.)
# we need to set the parameter requires_grad = True if we'll get grad
w, b = torch.tensor(2.,requires_grad=True), torch.tensor(3.,requires_grad=True)

In [35]:
# arithmetic operations
y = w * x + b
y, y.dtype

(tensor(5., grad_fn=<AddBackward0>), torch.float32)

In [36]:
# To compute the derivatives, we can call the .backward method on our result y.
# call backward()
y.backward()

In [38]:
# show gradidents
x.grad,w.grad,b.grad
# showing grad before .backward() will return None

(None, tensor(1.), tensor(1.))

# Interoperability with Numpy

In [39]:
import numpy as np

In [40]:
x = np.array([[1,2],[3,4.]])
x, x.shape, x.dtype

(array([[1., 2.],
        [3., 4.]]), (2, 2), dtype('float64'))

In [41]:
# Convert Numpy array to torch tensor
x_tensor = torch.from_numpy(x)
x_tensor

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [42]:
# Convert torch tensor to numpy array
x_numpy = x_tensor.numpy()
x_numpy

array([[1., 2.],
       [3., 4.]])